---
driver:
  name: vagrant
  require_chef_omnibus: 12.5
  provision: true
  vagrantfiles:
    - vagrant.rb


provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[jlaws::default]
  - name: instance-status
    run_list:
      - recipe[test-jlaws::default]
    attributes:
      # We explicity look for these node level attributes in the cookbook
      # if they don't exist we fall back to aws-sdk's use of IAM instnance
      # credentials
      <%= "aws_access_key_id: #{ENV['AWS_ACCESS_KEY_ID']}" %>
      <%= "aws_secret_access_key: #{ENV['AWS_SECRET_ACCESS_KEY']}" %>
  - name: secrets-manager
    run_list:
      - recipe[test-jlaws::secrets-manager]
    attributes:
      # We explicity look for these node level attributes in the cookbook
      # if they don't exist we fall back to aws-sdk's use of IAM instnance
      # credentials
      <%= "aws_access_key_id: #{ENV['AWS_ACCESS_KEY_ID']}" %>
      <%= "aws_secret_access_key: #{ENV['AWS_SECRET_ACCESS_KEY']}" %>
