---
driver:
  name: vagrant
  require_chef_omnibus: 12.5
  provision: true
  vagrantfiles:
    - vagrant.rb


provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[jlaws::default]
  - name: withxml
    run_list:
      - recipe[xml::default]
      - recipe[jlaws::default]
    attributes:
    # Test the instance-status library
  - name: instance-status
    run_list:
      - recipe[instance-status::default]
    attributes:
      <%= "aws_access_key_id: #{ENV['AWS_ACCESS_KEY_ID']}" %>
      <%= "aws_secret_access_key: #{ENV['AWS_SECRET_ACCESS_KEY']}" %>
